### ISSUE TITLE
Generator Crashed

### ISSUE THREAD

**Issue by hewenhan** [yownas/shift-attention#13]
SD_webui 1.5

```python
Error completing request
Arguments: ('task(4n43wglo263o2ii)', 0, 'masterpiece, best quality,pixel art,low contrast,\n(Schwarzenegger:0~1), (upper_body:0~1), (come_out_from:0~1), (clouds), (starry_sky), (open_mouth:0~1), (UZI:0~1)\n<lora:c64Graphics_v10:0.8>', 'ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, extra limbs, disfigured, deformed, body out of frame, blurry, bad anatomy, blurred, watermark, grainy, signature, cut off, draft, jagged lines', [], <PIL.Image.Image image mode=RGBA size=960x569 at 0x213AE092FB0>, None, None, None, None, None, None, 28, 17, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.68, 2372617705.0, -1.0, 0, 0, 0, False, 512, 904, 2, 0, 32, 0, '', '', '', [], 10, False, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, False, True, True, False, 1536, 96, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <controlnet.py.UiControlNetUnit object at 0x00000213AE091690>, <controlnet.py.UiControlNetUnit object at 0x00000213ADBD7910>, <controlnet.py.UiControlNetUnit object at 0x00000213AE0A4E80>, <controlnet.py.UiControlNetUnit object at 0x00000213ADBD64A0>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, 50, 10.0, 10.0, True, 0.0, 'Lanczos', 1, 0, 0, 75, 0.0001, 0.0, False, True, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "H:\backup\AI_P\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\backup\AI_P\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\backup\AI_P\stable-diffusion-webui\modules\img2img.py", line 170, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "H:\backup\AI_P\stable-diffusion-webui\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "H:\backup\AI_P\stable-diffusion-webui\extensions\shift-attention\scripts\shift_attention.py", line 198, in run
    prompts += [(prompt, negprompt, subseed, new_cfg_scale)]
UnboundLocalError: local variable 'new_cfg_scale' referenced before assignment
```

**Comment by yownas** [comment]
Oh. Sorry, missed setting that value to None before parsing the prompt. It should be fixed now.
